#!/bin/bash

# FinSage AI - Render Deployment Helper Script
# This script helps prepare and verify deployment to Render

echo "🚀 FinSage AI - Render Deployment Preparation"
echo "=============================================="
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if we're in the right directory
if [ ! -f "backend/main.py" ]; then
    echo -e "${RED}❌ Error: Please run this script from the FinSage-AI root directory${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Directory check passed${NC}"
echo ""

# Check if git is initialized
if [ ! -d ".git" ]; then
    echo -e "${YELLOW}⚠️  Git not initialized. Initializing...${NC}"
    git init
    git add .
    git commit -m "Initial commit for Render deployment"
fi

echo -e "${GREEN}✅ Git repository ready${NC}"
echo ""

# Check for required files
echo "📋 Checking required files..."
required_files=(
    "backend/main.py"
    "backend/requirements.txt"
    "backend/render.yaml"
    "backend/.env.example"
)

missing_files=0
for file in "${required_files[@]}"; do
    if [ -f "$file" ]; then
        echo -e "${GREEN}  ✓ $file${NC}"
    else
        echo -e "${RED}  ✗ $file (MISSING)${NC}"
        missing_files=$((missing_files + 1))
    fi
done

if [ $missing_files -gt 0 ]; then
    echo -e "${RED}❌ Missing $missing_files required file(s)${NC}"
    exit 1
fi

echo -e "${GREEN}✅ All required files present${NC}"
echo ""

# Check git status
echo "📊 Checking git status..."
if [ -n "$(git status --porcelain)" ]; then
    echo -e "${YELLOW}⚠️  You have uncommitted changes:${NC}"
    git status --short
    echo ""
    read -p "Do you want to commit these changes? (y/n) " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        git add .
        read -p "Enter commit message: " commit_msg
        git commit -m "$commit_msg"
        echo -e "${GREEN}✅ Changes committed${NC}"
    fi
else
    echo -e "${GREEN}✅ No uncommitted changes${NC}"
fi
echo ""

# Check for GitHub remote
echo "🔗 Checking GitHub remote..."
if git remote get-url origin &> /dev/null; then
    remote_url=$(git remote get-url origin)
    echo -e "${GREEN}✅ GitHub remote configured: $remote_url${NC}"
    
    read -p "Push to GitHub now? (y/n) " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        git push origin main
        echo -e "${GREEN}✅ Pushed to GitHub${NC}"
    fi
else
    echo -e "${YELLOW}⚠️  No GitHub remote configured${NC}"
    echo ""
    echo "To add a remote:"
    echo "  git remote add origin https://github.com/YOUR_USERNAME/FinSage-AI.git"
    echo "  git push -u origin main"
fi
echo ""

# Environment variables checklist
echo "📝 Environment Variables Checklist"
echo "=================================="
echo ""
echo "Make sure you have these values ready for Render:"
echo ""
echo -e "${YELLOW}Required:${NC}"
echo "  • MYSQL_HOST (TiDB Cloud host)"
echo "  • MYSQL_PORT (usually 4000)"
echo "  • MYSQL_USER (your database user)"
echo "  • MYSQL_PASSWORD (your database password)"
echo "  • MYSQL_DATABASE (usually 'test')"
echo "  • OPENAI_API_KEY (your OpenAI API key)"
echo ""
echo -e "${YELLOW}Auto-generated by Render:${NC}"
echo "  • JWT_SECRET_KEY (click 'Generate' in Render)"
echo ""
echo -e "${YELLOW}Optional:${NC}"
echo "  • CORS_ORIGINS (update after frontend deployed)"
echo ""

# Render deployment URL
echo ""
echo "🌐 Next Steps:"
echo "=============="
echo ""
echo "1. Go to https://render.com and sign in"
echo "2. Click 'New +' → 'Web Service'"
echo "3. Connect your GitHub repository: FinSage-AI"
echo "4. Configure:"
echo "   - Name: finsage-api"
echo "   - Root Directory: backend"
echo "   - Build Command: pip install --upgrade pip && pip install -r requirements-render.txt"
echo "   - Start Command: uvicorn main:app --host 0.0.0.0 --port \$PORT --workers 1"
echo "5. Add all environment variables listed above"
echo "6. Click 'Create Web Service'"
echo ""
echo "📖 For detailed instructions, see: RENDER_DEPLOYMENT.md"
echo ""

# Test backend locally
echo "🧪 Quick Local Test"
echo "==================="
read -p "Test backend locally before deploying? (y/n) " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Starting backend server..."
    cd backend
    
    # Check if virtual environment exists
    if [ ! -d "../.venv" ]; then
        echo -e "${RED}❌ Virtual environment not found${NC}"
        echo "Create one with: python -m venv .venv"
        exit 1
    fi
    
    source ../.venv/bin/activate
    
    # Install dependencies
    echo "Installing dependencies..."
    pip install -q -r requirements.txt
    
    # Start server in background
    echo "Starting server on http://localhost:8000..."
    python main.py &
    SERVER_PID=$!
    
    # Wait for server to start
    sleep 5
    
    # Test health endpoint
    echo "Testing health endpoint..."
    response=$(curl -s http://localhost:8000/api/finance/health)
    
    if echo "$response" | grep -q "healthy"; then
        echo -e "${GREEN}✅ Backend is working!${NC}"
        echo "Response: $response"
    else
        echo -e "${RED}❌ Backend test failed${NC}"
        echo "Response: $response"
    fi
    
    # Stop server
    kill $SERVER_PID 2>/dev/null
    cd ..
fi

echo ""
echo -e "${GREEN}🎉 Deployment preparation complete!${NC}"
echo ""
echo "Your backend is ready to deploy on Render!"
echo "Follow the guide in RENDER_DEPLOYMENT.md for step-by-step instructions."
echo ""
